baseurl: ""

# jekyll-seo-tag
title: SenseiCode
description: 教育とテクノロジーについて。
twitter:
  username: senseicode
facebook:
  admins: 1227210274
author:
  twitter: chibicode
logo: /images/og-image.png

future: true

gems:
  - jekyll-sitemap
  # Needed to customize. Same as this:
  # https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/template.html
  # but this line is commented out:
  # <link rel="canonical" href="{{ page.url | replace:'/index.html','/' | absolute_url }}" />
  # Uses feed_meta only
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - "src"
  - "README.md"
  - "LICENSE.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "package.json"
  - "webpack.config.js"
  - "npm-debug.log"
  - "server.js"
  - "Procfile"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      draft: false
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
